In [3]:
import numpy as np
a2d=np.array([[1,2,3,4],[5,6,7,8]])
c=a2d<5
print(c)

[[ True  True  True  True]
 [False False False False]]


In [5]:
d=a2d!=6
print(d)

[[ True  True  True  True]
 [ True False  True  True]]


In [7]:
e=a2d==5
print(e)

[[False False False False]
 [ True False False False]]


In [10]:
row_sum=np.apply_along_axis(np.sum, axis=0,arr=a2d)
print(row_sum)

col_sum=np.apply_along_axis(np.sum, axis=1,arr=a2d)
print(col_sum)

[ 6  8 10 12]
[10 26]


In [18]:
f=np.arange(10,16).reshape([3,2])
print("Marix created using reshape : \n",f)
f.shape=(2,3)
print("Reshaped : \n",f)

Marix created using reshape : 
 [[10 11]
 [12 13]
 [14 15]]
Reshaped : 
 [[10 11 12]
 [13 14 15]]


In [23]:
a2d_to_a1d=f.ravel()
print(a2d_to_a1d)

print("Transpose : \n", f.transpose())

[10 11 12 13 14 15]
Transpose : 
 [[10 13]
 [11 14]
 [12 15]]


In [35]:
A=np.zeros([3,4])
print("A matrix : \n ", A)
B=np.ones([3,4])
print("B matrix : \n ", B)
C=np.hstack((A,B))
print("C matrix : \n ", C)
D=np.vstack((A,B))
print("D matrix : \n ", D)


A matrix : 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
B matrix : 
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
C matrix : 
  [[0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1.]]
D matrix : 
  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [58]:
e=np.array([1,2,3])
f=np.array([3,4,5])
g=np.array([6,7,8])
print(np.column_stack((e,f,g)))
print(np.row_stack((e,f,g)))

h=np.arange(16).reshape((4,4))
[z1,z2]=np.hsplit(h,2)
print("hsplit \n", z1, "\n", z2)

i=np.arange(16).reshape((4,4))
[x,y]=np.vsplit(i,2)
print("vsplit \n", x,"\n",y)

j=np.arange(16).reshape((4,4))
[z4,z5,z6]=np.split(j,[1,3],axis=1)
print("split \n", z4,"\n",z5,"\n",z6)

[[1 3 6]
 [2 4 7]
 [3 5 8]]
[[1 2 3]
 [3 4 5]
 [6 7 8]]
hsplit 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
vsplit 
 [[0 1 2 3]
 [4 5 6 7]] 
 [[ 8  9 10 11]
 [12 13 14 15]]
split 
 [[ 0]
 [ 4]
 [ 8]
 [12]] 
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]] 
 [[ 3]
 [ 7]
 [11]
 [15]]


In [60]:
k=np.arange(16).reshape((4,4))
[b1,c1,d1]=np.split(k, [1,3], axis=0)
print(b1,"\n",c1,"\n",d1)

[[0 1 2 3]] 
 [[ 4  5  6  7]
 [ 8  9 10 11]] 
 [[12 13 14 15]]


In [83]:
arr1=np.arange(5)
arr2=np.arange(15).reshape((3,5))
print("arr 1 : ", arr1)
print("arr 2 : \n", arr2)

print(arr1+arr2)

age=np.dtype([('age', 'i4')])

l=np.array([(47,),(50,),(28,)], dtype=age)

print("Age Vectorization : ",l['age'])



workers=np.dtype([('name', 'U20'),('age', 'i1'),('salary','i4'), ('ocuupation', 'U30')])
w=np.array([('John',23,30000,'Carpenter'),('Smith',28,35000,'Mechanic'),('Alex',25,27000,'Driver')], dtype=workers)
print(w[2])


arr 1 :  [0 1 2 3 4]
arr 2 : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  2  4  6  8]
 [ 5  7  9 11 13]
 [10 12 14 16 18]]
Age Vectorization :  [47 50 28]
('Alex', 25, 27000, 'Driver')
