Python NumPy is a general-purpose array processing package which provides tools for handling the n-dimensional arrays. It provides various computing tools such as comprehensive mathematical functions, linear algebra routines. NumPy provides both the flexibility of Python and the speed of well-optimized compiled C code. It’s easy to use syntax makes it highly accessible and productive for programmers from any background.


NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python. It is open-source software.


Arrays in NumPy

NumPy’s main object is the homogeneous multidimensional array.

    It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.
    In NumPy, dimensions are called axes. The number of axes is rank.
    NumPy’s array class is called ndarray. It is also known by the alias array.

In [35]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,9]]) 
print(arr)

print("Type of numpy array : ", type(arr))

print(arr.dtype)

print("Dimensions of array (1D,2D) : ",arr.ndim)

print("Array size (no of ele ): ", arr.size)
print("Array order (mxn) : ", arr.shape)
arr2=np.arange(0,12)
print(arr2)
arr3=np.arange(101,113).reshape((4,3))
print("Array 4x3 : \n", arr3)
arr4=np.arange(101,113).reshape((3,4))
print("Array 3x4 : \n", arr4)
arr2=arr2.reshape(4,3)
print("Reshaped 1D arr2 : \n", arr2)


[[1 2 3 4]
 [5 6 7 9]]
Type of numpy array :  <class 'numpy.ndarray'>
int64
Dimensions of array (1D,2D) :  2
Array size (no of ele ):  8
Array order (mxn) :  (2, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Array 4x3 : 
 [[101 102 103]
 [104 105 106]
 [107 108 109]
 [110 111 112]]
Array 3x4 : 
 [[101 102 103 104]
 [105 106 107 108]
 [109 110 111 112]]
Reshaped 1D arr2 : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


NumPy Array Creation

1. You can create an array from a regular Python list or tuple using the array() function.

In [39]:
arr5=np.array([[10,20],[30,40]], dtype='float')
print(arr5)

[[10. 20.]
 [30. 40.]]


In [47]:
# 2. Create array with all zeros 

zero = np.zeros((3, 4))
print("Initiliase arr with zero : \n",zero)

# Create a new array with constant value
const = np.full((3, 2), 10)
print("Initiliase arr with constant : \n", const)

Initiliase arr with zero : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Initiliase arr with constant : 
 [[10 10]
 [10 10]
 [10 10]]


In [44]:
# Array multiplication

z=[[1,2,3],[4,5,6],[7,8,9]]
x=[10,10,10]
print(np.matmul(z,x))
print(np.dot(z,x))

[ 60 150 240]
[ 60 150 240]


In [56]:
# 3. Array creation usng arange
a=np.arange(5)
print("Array a: ",a)
a+=1
print("Increment each element : ", a)
print(np.arange(0,31,5))


Array a:  [0 1 2 3 4]
Increment each element :  [1 2 3 4 5]
[ 0  5 10 15 20 25 30]


In [67]:
# 4. Array creation using linspace
equi_div=np.linspace(.5,10,20)
newarr=equi_div.reshape(5,4)
print("2D array : \n",newarr)
d3newarr=equi_div.reshape(5,4)
print(d3newarr)
print("3D array : \n",equi_div)

2D array : 
 [[ 0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4. ]
 [ 4.5  5.   5.5  6. ]
 [ 6.5  7.   7.5  8. ]
 [ 8.5  9.   9.5 10. ]]
[[ 0.5  1.   1.5  2. ]
 [ 2.5  3.   3.5  4. ]
 [ 4.5  5.   5.5  6. ]
 [ 6.5  7.   7.5  8. ]
 [ 8.5  9.   9.5 10. ]]
3D array : 
 [ 0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5 10. ]


In [ ]:
# 5. Reshaping array

