In [65]:
import numpy as np
arr=np.arange(0,12,2,float)
print(arr)
arr=arr.reshape(2,3)
print(arr)
a1=2
a2=5
a3=np.dot(a1,a2)
print(a3)
a4=3+5j
a5=5+7j
a6=np.dot(a4,a5)
print(a6)
print(a4*a5)

a7=np.array([1,2,3,4])
a8=np.arange(12,16)
print("a7 and a8", np.dot(a7,a8))

a9=np.array([[1,2,3],[4,5,6]])
a10=[[10,20,30],[40,50,60],[6,7,8]]
a11=np.dot(a9,a10)
print("--- a11dot  \n",a11)
a12=np.matmul(a9,a10)
print("--- multiply  \n",a12)

a13=[[10,11,12],[13,14,15],[16,17,18]]
print("all : ",a13[0:]) # all
print("first row : ", a13[:1]) # first row
print("3rd rowil 1 to 2 rows", a13[1:3][1:3])

a14=np.arange(10,19).reshape(3,3)
print("a14 = ", a14[1:2][0,1])
print("a14[[1,2],[1:2]] = ",a14[[1,2][1:2]])
print("2nd,3rd row and 2nd,3rd col : ",a14[1:3,1:3])
print("[[14 15] [17 18]] \n: ",a14[[1,2],1:3])
print(" [[10 11 12] [16 17 18]] :\n ",a14[[0,2],0:3])

[ 0.  2.  4.  6.  8. 10.]
[[ 0.  2.  4.]
 [ 6.  8. 10.]]
10
(-20+46j)
(-20+46j)
a7 and a8 140
--- a11dot  
 [[108 141 174]
 [276 372 468]]
--- multiply  
 [[108 141 174]
 [276 372 468]]
all :  [[10, 11, 12], [13, 14, 15], [16, 17, 18]]
first row :  [[10, 11, 12]]
3rd rowil 1 to 2 rows [[16, 17, 18]]
a14 =  14
a14[[1,2],[1:2]] =  [[16 17 18]]
2nd,3rd row and 2nd,3rd col :  [[14 15]
 [17 18]]
2nd,3rd row and 2nd,3rd col :  [[14 15]
 [17 18]]
2nd,3rd row and 2nd,3rd col :  [[10 11 12]
 [16 17 18]]


In [96]:
arr=np.array([1,2,3,4])
print(arr)
for i in arr:
    print(i)
    
arr2=np.array([[1,2],[3,4]])
print("\n",arr2)

print("2 for loop : ")
for i in arr2:
    for j in i:
        print(i,end=" ")
        
print("\n2 for loop 2nd : ")
for i in arr2:
    for j in i:
        print(j,end=" ")
        
print("\nnditer")
arr3=np.array([[1,2],[3,4]])
for i in np.nditer(arr3):
    print(i)
    
print("\nflat")
print(list(arr3.flat))

print("\nflat")
for i in arr3.flat:
    print(i)


[1 2 3 4]
1
2
3
4

 [[1 2]
 [3 4]]
2 for loop : 
[1 2] [1 2] [3 4] [3 4] 
2 for loop 2nd : 
1 2 3 4 
nditer
1
2
3
4

flat
[1, 2, 3, 4]

flat
1
2
3
4


ModuleNotFoundError: No module named 'pygame'

In [109]:
a2d=np.array([[1,2,3,4],[5,6,7,8]])
print("a2d<5 = ", a2d<5)

a2d=np.array([[1,2,3,4],[5,6,7,8]])
print("\na2d=!3", a2d!=5)

c2=np.array([[1,2,3],[4,5,6]])
print(c2)
c=c2==5
print("\nc=c2==5",c)
print("Check if atleast one true value exists : ",c.any())
print("Check if all values are true : ",c.all())

a2d<5 =  [[ True  True  True  True]
 [False False False False]]

a2d=!3 [[ True  True  True  True]
 [False  True  True  True]]
[[1 2 3]
 [4 5 6]]

c=c2==5 [[False False False]
 [False  True False]]
Check if atleast one true value exists :  True
Check if all values are true :  False
